### ISSUE TITLE
The Loader component

### ISSUE THREAD

**Issue by leneti** [anthonyshew/mantine-figma#2]
**Link to desired Mantine component**
[Loader | Mantine](https://mantine.dev/core/loader/)

**Your contribution**
[Link to the Loader component in Figma](https://www.figma.com/file/edCstIEpRkcCOFSpJE76Hc/Mantine-UI-Component-Library-(Community)?node-id=1006%3A210175)

My contribution is:
- [x] Publically available

My first time actually getting hands on with Figma and contributing to a Figma kit repository, so decided to add something very simple, which I noticed wasn't in the kit yet. Feel very free to leave any feedback, thanks.

**Comment by anthonyshew** [comment]
Awesome!

@shewashley, can you take a look?

**Comment by shewashley** [comment]
Awesome job, @leneti! 

Here's a couple very minor things I fixed:

- Updated the component to match the Mantine's Blue color theme
- Updated the colors of the component to exclusively use established color styles (There were a couple layers with reduced opacity that broke the established color styles - we should refrain from doing this so that the library remains easily customizable. Instead of breaking the color style and reducing opacity, I would suggest using a lighter shade of your selected color.)
- Reordered size variant property values from xs-xl 

Thank you for your hard work. Your contribution has been published to the Community file!

**Comment by leneti** [comment]
@shewashley Thank you so much!

I have a question. I had the colour's opacity down to 50% because that's how Mantine does it IRL and the contribution guideline states the components need to be pixel perfect. Is it okay to simply use a lighter shade of the colour in the future? Given that with the reduced opacity the component would look a bit different when put on a dark background vs a light one, whereas with a lighter shade it will stay the same.

**Comment by leneti** [comment]
@shewashley I have a question. I had the colour's opacity down to 50% because that's how Mantine does it IRL and the contribution guideline states the components need to be pixel perfect. Is it okay to simply use a lighter shade of the colour in the future? Given that with the reduced opacity the component would look a bit different when put on a dark background vs a light one, whereas with a lighter shade it will stay the same.

**Comment by shewashley** [comment]
Great question - I didn't realize Mantine was using opacities IRL. Since that's the case, I created a few more color styles for the file and applied them appropriately. We do want to make sure we are using color styles throughout the file so that users of the library can edit colors in bulk easily. I appreciate your attention to detail!
